<template>
  <div class="info-input-panel">
    <el-form inline>
      <!-- 基础信息 -->
      <h3>基础信息</h3>
      <div style="border:1px solid #999999"></div>
      <el-form-item>
          姓名
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          性别
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          户籍
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          民族
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          身高
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          体重
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          血型
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          政治面貌
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          出生地
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          身份证号
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          保险情况
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          护照号
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          重大疾病史
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          qq
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          药物过敏史
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          志愿北京编号
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          蓝天uid
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          现住址
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          邮编
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          紧急联系人1
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          紧急联系人1关系
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          紧急联系人1联系方式
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          紧急联系人2
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          紧急联系人2关系
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          紧急联系人2联系方式
        <el-input></el-input>
      </el-form-item>
      <!-- 技能信息 -->
      <h3>技能信息</h3>
      <div style="border:1px solid #999999"></div>
      <el-form-item>
          医疗技能
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          野外技能
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          gps技能
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          无线电技能
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          身体技能
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          其他技能
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          救援经历
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          其他经历
        <el-input></el-input>
      </el-form-item>
      <!-- 教育信息 -->
      <h3>教育信息</h3>
      <div style="border:1px solid #999999"></div>
      <el-form-item>
          最高教育
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          教育时间
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          教育学校
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          教育专业
        <el-input></el-input>
      </el-form-item>
      <!-- 职业信息 -->
      <h3>职业信息</h3>
      <div style="border:1px solid #999999"></div>
      <el-form-item>
          职业时间
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          职业部门
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          职业公司
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          职业地址
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          个人简述
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          活动时长
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          职务
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          队务编号
        <el-input></el-input>
      </el-form-item>
      <el-form-item>
          照片地址
        <el-input></el-input>
      </el-form-item>
    </el-form>
  </div>
</template>
<style lang="scss" scoped>
.info-input-panel {
  padding: 20px;
}
.el-input {
  display: inline-block !important;
  width: 200px;
}
</style>